### ISSUE TITLE
AttributeError: type object 'AudioAdapter' has no attribute 'default'

### ISSUE THREAD

**Issue by SylviaZiyaZhou** [Music-and-Culture-Technology-Lab/omnizart#43]
2021-09-28 20:56:14 Loading model...
2021-09-28 20:56:14 Using built-in model c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\checkpoints/music/music_piano for transcription.
2021-09-28 20:56:16 Extracting feature...
Traceback (most recent call last):
  File "c:\users\dange\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dange\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dange\AppData\Local\Programs\Python\Python36\Scripts\omnizart.exe\__main__.py", line 7, in <module>
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dange\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\cli\music\transcribe.py", line 30, in transcribe
    music.app.transcribe(input_audio, model_path, output=output)
  File "c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\music\app.py", line 108, in transcribe
    harmonic=model_settings.feature.harmonic
  File "c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\feature\wrapper_func.py", line 20, in extract_cfp_feature
    z, spec, gcos, ceps, _ = extract_cfp(audio_path, **kwargs)
  File "c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\feature\cfp.py", line 305, in extract_cfp
    x, fs = load_audio(filename, sampling_rate=down_fs)
  File "c:\users\dange\appdata\local\programs\python\python36\lib\site-packages\omnizart\io.py", line 76, in load_audio
    audio_loader = adapter.AudioAdapter.default()
AttributeError: type object 'AudioAdapter' has no attribute 'default'

I have met this problem when using the music transcribe module. Is there something wrong with the 'AudioAdapter' module?

**Comment by BreezeWhite** [comment]
It's due to the version of `spleeter` used in omnizart. After updating the `spleeter` to the newest version, the problem should be solved.
