### ISSUE TITLE
Installing error on windows?

### ISSUE THREAD

**Issue by krigeta** [Music-and-Culture-Technology-Lab/omnizart#57]
Hello, i am getting this error while installing using PowerShell?

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-_mbv3wia\\llvmlite_18d27f538834480b8c1beb905a73a261\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-_mbv3wia\\llvmlite_18d27f538834480b8c1beb905a73a261\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-_xfi3jri\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\USER\AppData\Local\Programs\Python\Python39\Include\llvmlite'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\USER\AppData\Local\Temp\pip-install-_mbv3wia\llvmlite_18d27f538834480b8c1beb905a73a261\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 368, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\USER\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-_mbv3wia\\llvmlite_18d27f538834480b8c1beb905a73a261\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-_mbv3wia\\llvmlite_18d27f538834480b8c1beb905a73a261\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\USER\AppData\Local\Temp\pip-record-_xfi3jri\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\USER\AppData\Local\Programs\Python\Python39\Include\llvmlite' Check the logs for full command output.
```

**Comment by BreezeWhite** [comment]
It says it cannot find python.exe under C:\\Users\\USER\\AppData\\Local\\Programs\\Python\\Python39.

**Comment by BreezeWhite** [comment]
Not relevant to omnizart. Close this issue.
