### ISSUE TITLE
Problem with model_to/from_yaml

### ISSUE THREAD

**Issue by ycollet** [Music-and-Culture-Technology-Lab/omnizart#59]
I installed omnizart from pip on Fedora 33.
When running the command:
$ omnizart drum transcribe --output drum.mid File.mp3
I've got the following error message:
```
Traceback (most recent call last):
  File "/home/collette/python/omnizart/bin/omnizart", line 8, in <module>
    sys.exit(entry())
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/cli/drum/transcribe.py", line 26, in transcribe
    drum.app.transcribe(input_audio, model_path, output=output)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/drum/app.py", line 68, in transcribe
    model, model_settings = self._load_model(model_path, custom_objects=self.custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/base.py", line 30, in _load_model
    model = self._get_model_from_yaml(arch_path, custom_objects=custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/base.py", line 79, in _get_model_from_yaml
    return model_from_yaml(open(arch_path, "r").read(), custom_objects=custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/keras/saving/model_config.py", line 74, in model_from_yaml
    raise RuntimeError(
RuntimeError: Method `model_from_yaml()` has been removed due to security risk of arbitrary code execution. Please use `Model.to_json()` and `model_from_json()` instead.
```

**Comment by BreezeWhite** [comment]
What's the version of omnizart?

**Comment by ycollet** [comment]
Oups, sorry, here is the info. This is the last version found on pip:
$ pip list | grep omnizart
omnizart                     0.1.0

**Comment by BreezeWhite** [comment]
Could you run `pip install -U omnizart` and `omnizart download-checkpoint` after the upgrade, then see if the problem still exists?

**Comment by ycollet** [comment]
I ran!
$ pip install -U omnizart
Nothing got updated because I performed the installation yesterday :)

Then I done:
$ omnizart download-checkpoints

And the problem is still triggered by the following command:
```
$ omnizart drum transcribe --output dracula_drum.mid New\ Order-Dracula\'s\ Castle\ -\ YouTube.mp3 
2021-12-29 08:26:12 Extracting feature...
/home/collette/python/omnizart/lib/python3.9/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/home/collette/python/omnizart/lib/python3.9/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/home/collette/python/omnizart/lib64/python3.9/site-packages/madmom/features/downbeats.py:287: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  best = np.argmax(np.asarray(results)[:, 1])
/home/collette/python/omnizart/lib64/python3.9/site-packages/madmom/features/downbeats.py:287: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  best = np.argmax(np.asarray(results)[:, 1])
2021-12-29 08:30:18 Loading model...
2021-12-29 08:30:18 Using built-in model /home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/./checkpoints/drum/drum_keras for transcription.
Traceback (most recent call last):
  File "/home/collette/python/omnizart/bin/omnizart", line 8, in <module>
    sys.exit(entry())
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/cli/drum/transcribe.py", line 26, in transcribe
    drum.app.transcribe(input_audio, model_path, output=output)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/drum/app.py", line 68, in transcribe
    model, model_settings = self._load_model(model_path, custom_objects=self.custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/base.py", line 30, in _load_model
    model = self._get_model_from_yaml(arch_path, custom_objects=custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/omnizart/base.py", line 79, in _get_model_from_yaml
    return model_from_yaml(open(arch_path, "r").read(), custom_objects=custom_objects)
  File "/home/collette/python/omnizart/lib/python3.9/site-packages/keras/saving/model_config.py", line 74, in model_from_yaml
    raise RuntimeError(
RuntimeError: Method `model_from_yaml()` has been removed due to security risk of arbitrary code execution. Please use `Model.to_json()` and `model_from_json()` instead.
```

**Comment by BreezeWhite** [comment]
This seems like the version is still the old one. How about `pip uninstall omnizart` and `pip install git+https://github.com/Music-and-Culture-Technology-Lab/omnizart`? Directly install omnizart from github. Also could you run `pip show omnizart` after the installation?

**Comment by ycollet** [comment]
Thanks, installation from github works. I needed to install cython and numpy manually in my virtualenv (and rust + cargo too).
I also needed to compile a compatible version of python (3.6.13) from sources because Fedora 33 has Python 3.9.9.
Here is the result of pip show:
```
$ pip show omnizart
Name: omnizart
Version: 0.5.0
Summary: Omniscient Mozart, being able to transcribe everything in the music.
Home-page: https://sites.google.com/view/mctl/home
Author: BreezeWhite
Author-email: miyashita2010@tuta.io
License: MIT
Location: /home/collette/python/omnizart/lib/python3.6/site-packages
Requires: click, jsonschema, librosa, madmom, mir_eval, pillow, pretty_midi, pyfluidsynth, pyyaml, spleeter, tensorflow, tqdm, urllib3, vamp
Required-by: 
```
Thanks a lot for your help !

**Comment by BreezeWhite** [comment]
Good to hear that!
