### ISSUE TITLE
Unable to install omnizart in linux and windows

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Music-and-Culture-Technology-Lab/omnizart#73]
Every time, It shows ms those errors when trying to install omnizart using pip (python3.9)
`Building wheels for collected packages: numba, madmom, pretty_midi, vamp, audioread, llvmlite, resampy
  Building wheel for numba (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ................... (Delected some logs)..................
  ild/lib.linux-x86_64-3.10/numba/cuda/tests/cudadrv/data
      running build_ext
      building 'numba._dynfunc' extension
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules winreg, win32api or win32con are installed.
      C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/numba
      compile options: '-I/usr/include/python3.10 -c'
      extra options: '-g'
      x86_64-linux-gnu-gcc: numba/_dynfuncmod.c
      x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/numba/_dynfuncmod.o -o build/lib.linux-x86_64-3.10/numba/_dynfunc.cpython-310-x86_64-linux-gnu.so
      building 'numba._dispatcher' extension
      C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      creating build/temp.linux-x86_64-3.10/numba/typeconv
      compile options: '-I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.10 -c'
      x86_64-linux-gnu-gcc: numba/_dispatcher.cx86_64-linux-gnu-gcc: numba/_dispatcherimpl.cpp
      
      x86_64-linux-gnu-gcc: numba/_hashtable.cx86_64-linux-gnu-gcc: numba/_typeof.c
      
      numba/_dispatcher.c: In function ‘call_trace’:
      numba/_dispatcher.c:26:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
         26 |     tstate->use_tracing = 0;
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c:28:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
         28 |     tstate->use_tracing = ((tstate->c_tracefunc != NULL)
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c: In function ‘call_cfunc’:
      numba/_dispatcher.c:301:17: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        301 |     if (tstate->use_tracing && tstate->c_profilefunc)
            |                 ^~~~~~~~~~~
            |                 tracing
      numba/_dispatcher.c: In function ‘Dispatcher_call’:
      numba/_dispatcher.c:507:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘use_tracing’; did you mean ‘tracing’?
        507 |     if (ts->use_tracing && ts->c_profilefunc)
            |             ^~~~~~~~~~~
            |             tracing
      numba/_dispatcher.c: In function ‘call_cfunc’:
      numba/_dispatcher.c:349:1: warning: control reaches end of non-void function [-Wreturn-type]
        349 | }
            | ^
      x86_64-linux-gnu-gcc: numba/typeconv/typeconv.cpp
      error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.10 -c numba/_dispatcher.c -o build/temp.linux-x86_64-3.10/numba/_dispatcher.o" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  Building wheel for madmom (setup.py) ... done
  Created wheel for madmom: filename=madmom-0.16.1-cp310-cp310-linux_x86_64.whl size=21272880 sha256=a608f657428c6fb0f34d4a2ff9c40298ef5da49da8230a4f6bcfb8a7362995a0
  Stored in directory: /root/.cache/pip/wheels/87/18/20/105f9248e5f504f5ab190338516558cacaf6d5d7fadd5e7947
  Building wheel for pretty_midi (setup.py) ... done
  Created wheel for pretty_midi: filename=pretty_midi-0.2.9-py3-none-any.whl size=5591954 sha256=481a0857293048ec4b327b87ea5cf8da6cc2d3ae33d00f81d21bc471b140aff5
  Stored in directory: /root/.cache/pip/wheels/f5/05/68/55f44833c1801964b3ef0881e1798952bf53352a89d3a5932c
  Building wheel for vamp (setup.py) ... done
  Created wheel for vamp: filename=vamp-1.1.0-cp310-cp310-linux_x86_64.whl size=1705732 sha256=71bec5754bb26ee9eecad46613dd4139af801d607d36016dd5382b83b3480f61
  Stored in directory: /root/.cache/pip/wheels/36/9e/b1/230ac612a8aa718cf3e2485eac386ae72a4da61d7c31ac4bb2
  Building wheel for audioread (setup.py) ... done
  Created wheel for audioread: filename=audioread-2.1.9-py3-none-any.whl size=23153 sha256=ae2038f6bacba83ca8c426aade5fcbbbbfcaa95d5278d6eab944706ca281fc63
  Stored in directory: /root/.cache/pip/wheels/66/b4/4e/a554aa3e95c6d113b3eebe0e1d81ea6b075566fd4a1fca0307
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      /usr/bin/python3.10 /tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 168, in <module>
          main()
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 158, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/usr/bin/python3.10' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
  Building wheel for resampy (setup.py) ... done
  Created wheel for resampy: filename=resampy-0.2.2-py3-none-any.whl size=320730 sha256=25b9bbb71e1e9bf98be424a3e227f0bfd5e9a9748a1f55ae649e7016d1157e40
  Stored in directory: /root/.cache/pip/wheels/e5/a0/79/29e61754e5b3941ad4c7d01bf5bea99768e64e4bdd3180f32b
Successfully built madmom pretty_midi vamp audioread resampy
Failed to build numba llvmlite
Installing collected packages: vamp, tensorboard-plugin-wit, mido, llvmlite, libclang, keras, flatbuffers, audioread, wrapt, threadpoolctl, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, soundfile, rsa, pyfluidsynth, pretty_midi, pooch, opt-einsum, opencv-python, oauthlib, numba, keras-preprocessing, joblib, h5py, grpcio, google-pasta, gast, click, cachetools, astunparse, absl-py, scikit-learn, resampy, requests-oauthlib, madmom, google-auth, librosa, google-auth-oauthlib, tensorboard, tensorflow, omnizart
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
      running build_ext
      /usr/bin/python3.10 /tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 168, in <module>
          main()
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 158, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-i1cmbqt6/llvmlite_1c0fb6b0c7094099a3dc6ee225501b56/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/usr/bin/python3.10' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

**Comment by BreezeWhite** [comment]
Seems like it's an issue related to `numba`. Try running the command `pip install numba==0.50.1` and install again.

**Comment by SmoothKen** [comment]
The command ```pip install numba==0.50.1``` itself fails with similar errors as well.
