### ISSUE TITLE
Problem with Colab

### ISSUE THREAD

**Issue by PSCM** [Music-and-Culture-Technology-Lab/omnizart#88]
Hello. I've been trying to run some transcripts in Colab, however, I've been getting error messages. Here are the developed codes:

`!pip install -U pip`
`!pip install git+https://github.com/Music-and-Culture-Technology-Lab/omnizart`
`!omnizart download-checkpoints`

`import pandas as pd`
`import numpy as np`
`import os`
`import re`

`!bash process.bat '/content/drive/MyDrive/aug'` 

the processes file has the following code:
`for i in "$1"/*`
`do`
`  omnizart music transcribe "$i"`
`done`

I tried to import the library also adopting the following recommendation:

`!pip install -U pip`
`!pip install git+https://github.com/Music-and-Culture-Technology-Lab/omnizart.git`
`!omnizart download-checkpoints`
`!apt install fluidsynth`
`!pip install pyfluidsynth`
`!curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp`
`!chmod a+rx /usr/local/bin/yt-dlp`

Finally, the following error message comes up:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in method __contains__ of dict object at 0x7ffa41c7f7c0> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/omnizart", line 5, in <module>
    from omnizart.cli.cli import entry
  File "/usr/local/lib/python3.8/dist-packages/omnizart/cli/cli.py", line 16, in <module>
    import omnizart.constants.datasets as dset
  File "/usr/local/lib/python3.8/dist-packages/omnizart/constants/datasets.py", line 37, in <module>
    from omnizart.base import Label
  File "/usr/local/lib/python3.8/dist-packages/omnizart/base.py", line 13, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 34, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: initialization failed

**Comment by BreezeWhite** [comment]
I've encountered this before and fix it with upgrading the numpy by `pip install -U numpy`.

**Comment by BreezeWhite** [comment]
The colab should be fixed now.
