### ISSUE TITLE
This programs simply doesn't work...

### ISSUE THREAD

**Issue by jeanlopes** [Music-and-Culture-Technology-Lab/omnizart#92]
I pulled a docker image and just ran it.

This is the error:

´´´
2023-03-23 20:26:41 Loading model...
2023-03-23 20:26:41 Using built-in model /usr/local/lib/python3.6/dist-packages/omnizart/checkpoints/music/music_piano for transcription.
2023-03-23 20:26:49 Extracting feature...
Traceback (most recent call last):
  File "/usr/local/bin/omnizart", line 5, in <module>
    entry()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/omnizart/cli/music/transcribe.py", line 30, in transcribe
    music.app.transcribe(input_audio, model_path, output=output)
  File "/usr/local/lib/python3.6/dist-packages/omnizart/music/app.py", line 108, in transcribe
    harmonic=model_settings.feature.harmonic
  File "/usr/local/lib/python3.6/dist-packages/omnizart/feature/wrapper_func.py", line 23, in extract_cfp_feature
    z, spec, gcos, ceps, _ = cfp.extract_cfp(audio_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/omnizart/feature/cfp.py", line 306, in extract_cfp
    return _extract_cfp(x, fs, down_fs=fs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/omnizart/feature/cfp.py", line 234, in _extract_cfp
    x, samples, max_sample, fr, fs, Hop, h, fc, tc, g, bin_per_octave
  File "/usr/local/lib/python3.6/dist-packages/omnizart/feature/cfp.py", line 167, in parallel_extract
    for idx, (feat_list, slice_idx) in feat_generator:
  File "/usr/local/lib/python3.6/dist-packages/omnizart/utils.py", line 266, in parallel_generator
    yield future.result(), future_to_input[future]
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
´´´

**Comment by Szubie** [comment]
This error may have been because the docker container ran out of memory. I encountered this same issue running the program on a 5 minute audio clip while having only 2GB memory allocated to Docker; [increasing the memory allocated to Docker](https://docs.docker.com/desktop/settings-and-maintenance/settings/#resources) to 16GB allowed me to run the program without any issues.

Unfortunately there is not much feedback from the program about the cause of the crash, but you can check the output of `dmesg -T` in the Docker container following a crash to see if there is a mention of killing a process due to running out-of-memory.
