### ISSUE TITLE
Upgrade Replicate.com model

### ISSUE THREAD

**Issue by basicfeatures** [Music-and-Culture-Technology-Lab/omnizart#94]
> Uh oh! This model can't be run on Replicate because it was built with a version of Cog that is no longer supported. Consider opening an issue on [the model's GitHub repository](https://github.com/Music-and-Culture-Technology-Lab/omnizart) to see if it can be updated to use [a recent version of Cog](https://github.com/replicate/cog). If you need any help, please hop into our [Discord channel](https://discord.gg/replicate) or [email us](mailto:team@replicate.com) about it.

Thanks!

**Comment by osbre** [comment]
I was trying to get it running on Replicate, but there's a problem:


```
Validating model schema...

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/.pyenv/versions/3.8.18/lib/python3.8/site-packages/cog/__init__.py", line 1, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 48, in init pydantic.dataclasses

ImportError: cannot import name dataclass_transform

ⅹ Failed to get type signature: exit status 1
```

According to [this](https://github.com/great-expectations/great_expectations/issues/6486#issuecomment-1339836669) comment, it happens due to the newer Pydantic version and should be gone if you downgrade to 1.9.0.

I'm trying to downgrade Pydantic but don't have enough experience with the Python ecosystem to make it work. Here's my updated config.

```yaml
build:
  gpu: true
  python_version: "3.8"
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
    - "libsndfile1-dev"
    - "ffmpeg"
    - "fluidsynth"
    - "git"
  python_packages:
    - "ipython==7.30.1"
    - "numpy==1.21.4"
    - "pydantic<1.9.0"
  run:
    - pip install -U pip
    - pip install --upgrade cython
    - pip install omnizart
    - pip install pyfluidsynth

predict: "scripts/predict.py:Predictor"
```

Would appreciate it if someone picked it up from here.
